//
// File:  src/root/logger.idl
//
// Description: Interface for logger
//

/* The logger interface description */

/* our C++ datatypes and IDL4 datatypes  */
import "sdi/types.h";
#include <types.idl>
#include <iftaskserver.idl>

interface taskserver : IF_TASKSERVER {

};
