/*****************************************************************
 * Source file : keyboarddriver.idl
 * Platform    : V4 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.1.0 (roadrunner) on 16/07/2012 02:45
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include <sdi/sdi.h>
#include <sdi/constants.h>
#include <l4io.h>

#include <if/iflogging.h>
#include <if/iftaskserver.h>

#include "keyboarddriver.h"

L4_ThreadId_t loggerid;


int main(void)
{
        CORBA_Environment env(idl4_default_environment);

        loggerid = L4_nilthread;

        while (L4_IsNilThread(loggerid))
                loggerid = nameserver_lookup("/server/logger");

        IF_LOGGING_LogMessage((CORBA_Object)loggerid, "[KEYBOARDDRIVER] Registering", &env);

	driverserver_register("keyboard");

        IF_LOGGING_LogMessage((CORBA_Object)loggerid, "[KEYBOARDDRIVER] Registered...", &env);

        L4_ThreadId_t taskserverid = L4_nilthread;

        while (L4_IsNilThread(taskserverid))
                taskserverid = nameserver_lookup("/task");

	// Attach keyboard interrupt
	IF_TASKSERVER_attach_interrupt((CORBA_Object)taskserverid, 0x01, &env);

	IF_LOGGING_LogMessage((CORBA_Object)loggerid, "[KEYBOARDDRIVER] Registered Interrupt...", &env);

	keyboarddriver_server();
}

