//
// File:  src/root/logger.idl
//
// Description: Interface for logger
//

/* The logger interface description */

/* our C++ datatypes and IDL4 datatypes  */
import "sdi/types.h";
#include <types.idl>
#include <ifnaming.idl>
#include <iffile.idl>

[uuid(IF_DRIVERSERVER_ID)]
interface IF_DRIVERSERVER : IF_NAMING, IF_FILE {

        void register(in path_t path);
        void deregister();
};
