import "sdi/types.h";
#include <types.idl>
#include <ifnaming.idl>
#include <iffile.idl>

[uuid(IF_DRIVERSERVER_ID)]
interface IF_DRIVERSERVER : IF_NAMING {
	/** Register */
        void register(in path_t path);
        void deregister();
};
