//
// File:  if/locator.idl
//
// Description: Interface for name resolution
//

/* our datatypes & exceptions */
import "sdi/types.h";
#include <types.idl>

[uuid(IF_LOCATOR_ID)]
interface IF_LOCATOR {

    void Announce( in interfaceid_t type, in L4_ThreadId_t thread ) 
	raises (type_conflict); 
    void Locate( in interfaceid_t type, out L4_ThreadId_t thread );

};
