import "sdi/types.h";
#include <types.idl>

[uuid(IF_LOGGING_ID)]
interface IF_LOGGING {

	/**
	  Send the given message to the logger

	  @param message Log message
	*/
	void LogMessage( in logmessage_t message);
};
