import "sdi/types.h";

#include <types.idl>

[uuid(IF_NAMING_ID)]
interface IF_NAMING {
    exception NotFound {};

    /**
      Lookup the thread responsible for the given path

      @param path Path to lookup
      @param remaining The part of the path which could not be looked up by this server
             and has to be forwarded to the next one
      @return L4_nilthread on error, thread id of the next server to ask after this one
    */
    L4_ThreadId_t Lookup(in path_t path, out path_t remaining) raises (NotFound);
};
