import "sdi/types.h";
#include <types.idl>
#include <ifnaming.idl>

[uuid(IF_NAMESERVER_ID)]
interface IF_NAMESERVER : IF_NAMING {
	/**
	  Register the given path for the calling thread

	  @param path Path
	*/
	void register(in path_t path); 

	/**
	  Deregister the calling thread
	*/
	void deregister();
};
