//
// File:  if/locator.idl
//
// Description: Interface for name resolution
//

/* our datatypes & exceptions */
import "sdi/types.h";

#include <types.idl>
#include <ifnaming.idl>

[uuid(IF_NAMESERVER_ID)]
interface IF_NAMESERVER : IF_NAMING {

    void register(in path_t path);
    void unregister(in path_t path);
};
