import "sdi/types.h";

#include <types.idl>

[uuid(IF_NAMING_ID)]
interface IF_NAMING {
    exception NotFound {};

    L4_ThreadId_t Lookup(in path_t path, out path_t remaining) raises (NotFound);

};
