import "sdi/types.h";
#include <types.idl>

[uuid(IF_PAGER_ID)]
interface IF_PAGER {
    /**
       Page fault handler

       @param address Address space Id
       @param ip Faulting instruction pointer
       @param privileges Fault reason (r = read, w = write, x = execute)
       @param page Returned Fpage
    */
    [kernelmsg(idl4::pagefault)]
    void    pagefault(in L4_Word_t address,
                      in L4_Word_t ip,
                      in L4_Word_t privileges,
                      out fpage page);

    void alloc(in fpage page, in L4_Word_t size);
    void free(in fpage page);
};
