import "sdi/types.h";
#include <types.idl>

exception TCFault {};
exception LoaderFault {};
exception NoRights {};

[uuid(IF_TASK_ID)]
interface IF_TASK {
    int create_task(in string path) raises (LoaderFault,TCFault);
    int create_thread(in int ip, in int sp) raises (TCFault);
        
    void kill_task(in int taskid, in boolean adopt) raises (TCFault,NoRights);
    void kill_thread(in int threadid, in boolean adopt) raises (TCFault,NoRights);
    
    void set_priority(in int threadid, in int prio) raises (NoRights);
};
