//
// File:  if/types.idl
//
// Description: Basic IDL types for SDI
//


#ifndef _sdi_if_types_h__
#define _sdi_if_types_h__

/* our SDI C++ datatypes from include  */
import "sdi/types.h";


/* some IDL datatypes we might need */

typedef char interfaceid_t;
typedef string<256> logmessage_t;
typedef string<64> path_t;
typedef sequence<char> buffer_t;
typedef string<256> consolestring_t;

/* IDL interface consts */

const interfaceid_t IF_LOGGING_ID = 1;
const interfaceid_t IF_LOCATOR_ID = 2;
const interfaceid_t IF_TASK_ID = 3;
const interfaceid_t IF_NAMING_ID = 4;
const interfaceid_t IF_NAMESERVER_ID = 5;
const interfaceid_t IF_FILE_ID = 6;
const interfaceid_t IF_FILESERVER_ID = 7;
const interfaceid_t IF_DRIVERSERVER_ID = 8;
const interfaceid_t IF_CONSOLESERVER_ID = 9;
const interfaceid_t IF_KEYBOARDDRIVER_ID = 10;

const interfaceid_t MAX_INTERFACEID = 16;

/* Exceptions */

exception type_conflict {}; 

#endif /* _sdi_if_types_h__ */
