/*****************************************************************
 * Source file : driverserver.idl
 * Platform    : V4 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.1.0 (roadrunner) on 20/09/2012 13:31
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include "generated_server.h"

/* Interface driver */

IDL4_INLINE void  driver_register_implementation(CORBA_Object  _caller, const path_t  path, idl4_server_environment * _env)

{
  /* implementation of IF_DRIVERSERVER::register */
  
  return;
}

IDL4_PUBLISH_DRIVER_REGISTER(driver_register_implementation);

IDL4_INLINE void  driver_deregister_implementation(CORBA_Object  _caller, idl4_server_environment * _env)

{
  /* implementation of IF_DRIVERSERVER::deregister */
  
  return;
}

IDL4_PUBLISH_DRIVER_DEREGISTER(driver_deregister_implementation);

IDL4_INLINE L4_ThreadId_t  driver_Lookup_implementation(CORBA_Object  _caller, const path_t  path, path_t * remaining, idl4_server_environment * _env)

{
  L4_ThreadId_t  __retval = { local: { X: { 0, 0 } } };

  /* implementation of IF_NAMING::Lookup */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_LOOKUP(driver_Lookup_implementation);

IDL4_INLINE L4_Word_t  driver_get_file_id_implementation(CORBA_Object  _caller, const path_t  path, idl4_server_environment * _env)

{
  L4_Word_t  __retval = 0;

  /* implementation of IF_FILE::get_file_id */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_GET_FILE_ID(driver_get_file_id_implementation);

IDL4_INLINE L4_Word_t  driver_read_implementation(CORBA_Object  _caller, const L4_Word_t  file_id, const L4_Word_t  offset, const L4_Word_t  count, buf_t * buf, idl4_server_environment * _env)

{
  L4_Word_t  __retval = 0;

  /* implementation of IF_FILE::read */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_READ(driver_read_implementation);

IDL4_INLINE L4_Word_t  driver_write_implementation(CORBA_Object  _caller, const L4_Word_t  file_id, const L4_Word_t  offset, const L4_Word_t  count, const buf_t * buf, idl4_server_environment * _env)

{
  L4_Word_t  __retval = 0;

  /* implementation of IF_FILE::write */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_WRITE(driver_write_implementation);

IDL4_INLINE L4_Word_t  driver_get_file_size_implementation(CORBA_Object  _caller, const path_t  path, idl4_server_environment * _env)

{
  L4_Word_t  __retval = 0;

  /* implementation of IF_FILE::get_file_size */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_GET_FILE_SIZE(driver_get_file_size_implementation);

IDL4_INLINE L4_Word_t  driver_get_file_type_implementation(CORBA_Object  _caller, const path_t  path, idl4_server_environment * _env)

{
  L4_Word_t  __retval = 0;

  /* implementation of IF_FILE::get_file_type */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_GET_FILE_TYPE(driver_get_file_type_implementation);

IDL4_INLINE CORBA_boolean  driver_remove_implementation(CORBA_Object  _caller, const L4_Word_t  file_id, idl4_server_environment * _env)

{
  CORBA_boolean  __retval = 0;

  /* implementation of IF_FILE::remove */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_REMOVE(driver_remove_implementation);

IDL4_INLINE CORBA_boolean  driver_mkdir_implementation(CORBA_Object  _caller, const path_t  path, idl4_server_environment * _env)

{
  CORBA_boolean  __retval = 0;

  /* implementation of IF_FILE::mkdir */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_MKDIR(driver_mkdir_implementation);

IDL4_INLINE CORBA_boolean  driver_rmdir_implementation(CORBA_Object  _caller, const path_t  path, idl4_server_environment * _env)

{
  CORBA_boolean  __retval = 0;

  /* implementation of IF_FILE::rmdir */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_RMDIR(driver_rmdir_implementation);

IDL4_INLINE L4_Word_t  driver_get_dir_size_implementation(CORBA_Object  _caller, const path_t  path, idl4_server_environment * _env)

{
  L4_Word_t  __retval = 0;

  /* implementation of IF_FILE::get_dir_size */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_GET_DIR_SIZE(driver_get_dir_size_implementation);

IDL4_INLINE CORBA_boolean  driver_get_dir_entry_implementation(CORBA_Object  _caller, const path_t  path, const L4_Word_t  entry, path_t * buf, idl4_server_environment * _env)

{
  CORBA_boolean  __retval = 0;

  /* implementation of IF_FILE::get_dir_entry */
  
  return __retval;
}

IDL4_PUBLISH_DRIVER_GET_DIR_ENTRY(driver_get_dir_entry_implementation);

void * driver_vtable_4[DRIVER_DEFAULT_VTABLE_SIZE] = DRIVER_DEFAULT_VTABLE_4;
void * driver_vtable_6[DRIVER_DEFAULT_VTABLE_SIZE] = DRIVER_DEFAULT_VTABLE_6;
void * driver_vtable_8[DRIVER_DEFAULT_VTABLE_SIZE] = DRIVER_DEFAULT_VTABLE_8;
void * driver_vtable_discard[DRIVER_DEFAULT_VTABLE_SIZE] = DRIVER_DEFAULT_VTABLE_DISCARD;
void ** driver_itable[16] = { driver_vtable_discard, driver_vtable_discard, driver_vtable_discard, driver_vtable_discard, driver_vtable_4, driver_vtable_discard, driver_vtable_6, driver_vtable_discard, driver_vtable_8, driver_vtable_discard, driver_vtable_discard, driver_vtable_discard, driver_vtable_discard, driver_vtable_discard, driver_vtable_discard, driver_vtable_discard };

void  driver_server(void)

{
  L4_ThreadId_t  partner;
  L4_MsgTag_t  msgtag;
  idl4_msgbuf_t  msgbuf;
  long  cnt;

  idl4_msgbuf_init(&msgbuf);
  for (cnt = 0;cnt < DRIVER_STRBUF_SIZE;cnt++)
    idl4_msgbuf_add_buffer(&msgbuf, malloc(8000), 8000);

  while (1)
    {
      partner = L4_nilthread;
      msgtag.raw = 0;
      cnt = 0;

      while (1)
        {
          idl4_msgbuf_sync(&msgbuf);

          idl4_reply_and_wait(&partner, &msgtag, &msgbuf, &cnt);

          if (idl4_is_error(&msgtag))
            break;

          idl4_process_request(&partner, &msgtag, &msgbuf, &cnt, driver_itable[idl4_get_interface_id(&msgtag) & DRIVER_IID_MASK][idl4_get_function_id(&msgtag) & DRIVER_FID_MASK]);
        }
    }
}

void  driver_discard(void)

{
}

