//
// File:  src/memoryserver/memoryserver.idl
//
// Description: Interface for memoryserver
//

/* The logger interface description */

/* our C++ datatypes and IDL4 datatypes  */
import "sdi/types.h";
#include <types.idl>
#include <ifmemoryserver.idl>

interface memoryserver : IF_MEMORYSERVER {

};
