/*****************************************************************
 * Source file : consoleserver.idl
 * Platform    : V4 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.1.0 (roadrunner) on 15/07/2012 18:21
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include <sdi/sdi.h>
#include <sdi/constants.h>
#include "consoleserver-server.h"

#include <if/iflogging.h>

#include "consoleserver.h"


L4_ThreadId_t loggerid;


int main(void)
{
	CORBA_Environment env(idl4_default_environment);

	while (L4_IsNilThread(loggerid))
        	loggerid = nameserver_lookup("/server/logger");

	/* Register myself with the nameserver */
	nameserver_register("/server/console");
	IF_LOGGING_LogMessage((CORBA_Object)loggerid, "[CONSOLESERVER] Registered", &env);

	consoleserver_init();

	consoleserver_server();
}

