/*****************************************************************
 * Source file : nameserver.idl
 * Platform    : V4 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.1.0 (roadrunner) on 17/08/2012 12:17
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include <sdi/sdi.h>
#include <sdi/constants.h>
#include <l4io.h>

#include "fileserver.h"

int main(void)
{
	printf("fileserver Pager: %lx\n", L4_Pager().raw);

	fileserver_server();

	while(42)
	{
	}
}

